package features

// allFeatures is the complete catalog of available indicators/fields.
// Short descriptions are designed for UI hover tooltips - concise and immediately useful.
var allFeatures = []Feature{
	// Price (OHLCV)
	{
		ID:        "open",
		Name:      "Open",
		ShortDesc: "First traded price of the session (split-adjusted)",
		LongDesc:  "The first traded price of the trading session, split-adjusted. Used in gap calculations and candlestick patterns.",
		Category:  CategoryPrice,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/o/openprice.asp",
	},
	{
		ID:        "high",
		Name:      "High",
		ShortDesc: "Highest price during the session (split-adjusted)",
		LongDesc:  "The highest traded price during the session, split-adjusted. Used in volatility calculations and breakout detection.",
		Category:  CategoryPrice,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/h/high.asp",
	},
	{
		ID:        "low",
		Name:      "Low",
		ShortDesc: "Lowest price during the session (split-adjusted)",
		LongDesc:  "The lowest traded price during the session, split-adjusted. Used in support level identification and volatility calculations.",
		Category:  CategoryPrice,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/l/low.asp",
	},
	{
		ID:        "close",
		Name:      "Close",
		ShortDesc: "Last traded price of the session (split-adjusted)",
		LongDesc:  "The final traded price of the session, split-adjusted. Most commonly used price for technical analysis and indicator calculations.",
		Category:  CategoryPrice,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/c/closingprice.asp",
	},
	{
		ID:        "volume",
		Name:      "Volume",
		ShortDesc: "Shares traded during the session",
		LongDesc:  "Number of shares traded during the session. Note: free-tier IEX volume is a fraction of consolidated volume. Use dollar_vol for more reliable metrics.",
		Category:  CategoryVolume,
		DataType:  "volume",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/v/volume.asp",
	},

	// Trend - Simple Moving Averages
	{
		ID:        "sma5",
		Name:      "SMA 5",
		ShortDesc: "5-day average price - very short-term trend",
		LongDesc:  "The 5-day simple moving average of closing prices. Very short-term trend indicator. Useful for scalping and very short-term momentum.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},
	{
		ID:        "sma10",
		Name:      "SMA 10",
		ShortDesc: "10-day average price - short-term trend",
		LongDesc:  "The 10-day simple moving average of closing prices. Short-term trend indicator. Often used for swing trading signals.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},
	{
		ID:        "sma20",
		Name:      "SMA 20",
		ShortDesc: "20-day average price - short/medium trend",
		LongDesc:  "The 20-day simple moving average of closing prices. Short-to-medium term trend indicator. Often used as dynamic support/resistance and in Bollinger Bands.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},
	{
		ID:        "sma30",
		Name:      "SMA 30",
		ShortDesc: "30-day average price - medium-term trend",
		LongDesc:  "The 30-day simple moving average of closing prices. Medium-term trend indicator. Less common than SMA20 or SMA50.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},
	{
		ID:        "sma50",
		Name:      "SMA 50",
		ShortDesc: "50-day average price - medium-term trend",
		LongDesc:  "The 50-day simple moving average of closing prices. Medium-term trend indicator. Golden cross = SMA50 crosses above SMA200 (bullish signal).",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},
	{
		ID:        "sma100",
		Name:      "SMA 100",
		ShortDesc: "100-day average price - medium/long trend",
		LongDesc:  "The 100-day simple moving average of closing prices. Medium-to-long term trend indicator. Less commonly watched than SMA50 or SMA200.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},
	{
		ID:        "sma200",
		Name:      "SMA 200",
		ShortDesc: "200-day average price - long-term trend",
		LongDesc:  "The 200-day simple moving average of closing prices. The most widely watched long-term trend indicator. Price above SMA200 = bullish trend, below = bearish.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/sma.asp",
	},

	// Trend - Exponential Moving Averages
	{
		ID:        "ema10",
		Name:      "EMA 10",
		ShortDesc: "10-day weighted average - faster than SMA",
		LongDesc:  "The 10-day exponential moving average. More responsive to recent prices than SMA. Good for short-term trend following.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/e/ema.asp",
	},
	{
		ID:        "ema21",
		Name:      "EMA 21",
		ShortDesc: "21-day weighted average - fast short-term trend",
		LongDesc:  "The 21-day exponential moving average. Short-term trend with faster response than SMA20. Popular in Fibonacci-based trading.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/e/ema.asp",
	},
	{
		ID:        "ema50",
		Name:      "EMA 50",
		ShortDesc: "50-day weighted average - medium-term trend",
		LongDesc:  "The 50-day exponential moving average. Medium-term trend with faster response than SMA50. More weight on recent prices.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/e/ema.asp",
	},
	{
		ID:        "ema100",
		Name:      "EMA 100",
		ShortDesc: "100-day weighted average - medium/long trend",
		LongDesc:  "The 100-day exponential moving average. Medium-to-long term trend. More responsive than SMA100.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/e/ema.asp",
	},
	{
		ID:        "ema200",
		Name:      "EMA 200",
		ShortDesc: "200-day weighted average - long-term trend",
		LongDesc:  "The 200-day exponential moving average. Long-term trend with faster response than SMA200. More weight on recent prices.",
		Category:  CategoryTrend,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/e/ema.asp",
	},

	// Trend - Derived
	{
		ID:        "pct_from_sma50",
		Name:      "% From SMA 50",
		ShortDesc: "How far price is from 50-day average",
		LongDesc:  "Percentage distance of close from the 50-day SMA. Positive = above (bullish), negative = below (bearish). Useful for mean reversion strategies.",
		Category:  CategoryTrend,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/m/meanreversion.asp",
	},
	{
		ID:        "pct_from_sma200",
		Name:      "% From SMA 200",
		ShortDesc: "How far price is from 200-day average",
		LongDesc:  "Percentage distance of close from the 200-day SMA. Positive = above (bullish), negative = below (bearish). Key long-term trend metric.",
		Category:  CategoryTrend,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/m/meanreversion.asp",
	},
	{
		ID:        "ma_stack",
		Name:      "MA Stack",
		ShortDesc: "Perfect bullish EMA alignment (10>21>50>200)",
		LongDesc:  "Boolean: true when EMAs are in perfect bullish order (EMA10 > EMA21 > EMA50 > EMA200). Indicates strong, clean uptrend across all timeframes.",
		Category:  CategoryTrend,
		DataType:  "boolean",
		Sortable:  false,
		WikiURL:   "https://www.investopedia.com/terms/m/movingaverage.asp",
	},

	// Momentum
	{
		ID:        "rsi14",
		Name:      "RSI 14",
		ShortDesc: "Momentum oscillator (0-100): >70 overbought, <30 oversold",
		LongDesc:  "Relative Strength Index (14-day). Momentum oscillator measuring speed and change of price movements. Values 0-100. Above 70 = overbought (potential reversal), below 30 = oversold (potential bounce).",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/rsi.asp",
	},
	{
		ID:        "macd",
		Name:      "MACD",
		ShortDesc: "Momentum: 12-day EMA minus 26-day EMA",
		LongDesc:  "Moving Average Convergence Divergence line. EMA12 minus EMA26. Positive = bullish momentum, negative = bearish. Crossing zero = trend change.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/m/macd.asp",
	},
	{
		ID:        "macd_signal",
		Name:      "MACD Signal",
		ShortDesc: "9-day EMA of MACD - signal line",
		LongDesc:  "9-day EMA of the MACD line. MACD crossing above signal = bullish signal, crossing below = bearish signal.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/m/macd.asp",
	},
	{
		ID:        "macd_hist",
		Name:      "MACD Histogram",
		ShortDesc: "MACD minus signal - momentum strength",
		LongDesc:  "Difference between MACD and signal line. Positive and rising = strengthening bullish momentum. Negative and falling = strengthening bearish momentum.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/m/macd.asp",
	},
	{
		ID:        "stoch_k",
		Name:      "Stochastic %K",
		ShortDesc: "Fast stochastic (0-100): >80 overbought, <20 oversold",
		LongDesc:  "Fast stochastic oscillator. Compares closing price to price range over 14 periods. Values 0-100. Above 80 = overbought, below 20 = oversold.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/stochasticoscillator.asp",
	},
	{
		ID:        "stoch_d",
		Name:      "Stochastic %D",
		ShortDesc: "3-day average of %K - slower signal",
		LongDesc:  "3-day SMA of %K. Slower signal line for stochastic oscillator. %K crossing above %D = bullish signal.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/s/stochasticoscillator.asp",
	},
	{
		ID:        "willr14",
		Name:      "Williams %R",
		ShortDesc: "Momentum (-100 to 0): >-20 overbought, <-80 oversold",
		LongDesc:  "Williams %R (14-day). Momentum indicator similar to stochastic but inverted scale. Values -100 to 0. Above -20 = overbought, below -80 = oversold.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/w/williamsr.asp",
	},
	{
		ID:        "cci20",
		Name:      "CCI 20",
		ShortDesc: "Cyclical turns: >+100 strong uptrend, <-100 downtrend",
		LongDesc:  "Commodity Channel Index (20-day). Identifies cyclical turns and trend strength. Values typically -100 to +100. Above +100 = strong uptrend, below -100 = strong downtrend.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/c/commoditychannelindex.asp",
	},
	{
		ID:        "mfi14",
		Name:      "MFI 14",
		ShortDesc: "Volume-weighted RSI (0-100): >80 overbought, <20 oversold",
		LongDesc:  "Money Flow Index (14-day). Volume-weighted RSI. Values 0-100. Above 80 = overbought, below 20 = oversold. Uses price × volume for confirmation.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/m/moneyflow.asp",
	},
	{
		ID:        "roc10",
		Name:      "ROC 10",
		ShortDesc: "10-day price change % - short-term momentum",
		LongDesc:  "Rate of Change (10-day). Percentage change over 10 days. Positive = rising momentum, negative = falling. Simple momentum measure.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/rateofchange.asp",
	},
	{
		ID:        "roc20",
		Name:      "ROC 20",
		ShortDesc: "20-day price change % - medium-term momentum",
		LongDesc:  "Rate of Change (20-day). Percentage change over 20 days. Medium-term momentum. Less noisy than ROC10.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/rateofchange.asp",
	},
	{
		ID:        "adx14",
		Name:      "ADX 14",
		ShortDesc: "Trend strength (0-100): >25 strong trend, <20 weak",
		LongDesc:  "Average Directional Index (14-day). Measures trend strength regardless of direction. Values 0-100. Above 25 = strong trend, below 20 = weak/no trend. Does not indicate direction.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/a/adx.asp",
	},
	{
		ID:        "di_plus",
		Name:      "+DI",
		ShortDesc: "Uptrend strength (14-day) - part of ADX system",
		LongDesc:  "Positive Directional Indicator (14-day). Measures strength of uptrend. +DI > -DI = bullish. Used with ADX for trend following.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/a/adx.asp",
	},
	{
		ID:        "di_minus",
		Name:      "-DI",
		ShortDesc: "Downtrend strength (14-day) - part of ADX system",
		LongDesc:  "Negative Directional Indicator (14-day). Measures strength of downtrend. -DI > +DI = bearish. Used with ADX for trend following.",
		Category:  CategoryMomentum,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/a/adx.asp",
	},

	// Volatility
	{
		ID:        "atr14",
		Name:      "ATR 14",
		ShortDesc: "Volatility measure - used for stops & position sizing",
		LongDesc:  "Average True Range (14-day). Measures volatility. Higher ATR = more volatile. Commonly used for position sizing and stop-loss placement (e.g., 2× ATR stop).",
		Category:  CategoryVolatility,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/a/atr.asp",
	},
	{
		ID:        "atr_pct",
		Name:      "ATR %",
		ShortDesc: "ATR as % of price - normalized volatility",
		LongDesc:  "ATR14 divided by close. Normalizes volatility across different price levels. Allows comparison between $10 and $1000 stocks.",
		Category:  CategoryVolatility,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/a/atr.asp",
	},
	{
		ID:        "bb_upper",
		Name:      "Bollinger Upper",
		ShortDesc: "Upper band: SMA20 + 2σ - near = overbought",
		LongDesc:  "Upper Bollinger Band. SMA20 plus 2 standard deviations. Price near upper band = potentially overbought. Also used for volatility measurement.",
		Category:  CategoryVolatility,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/b/bollingerbands.asp",
	},
	{
		ID:        "bb_mid",
		Name:      "Bollinger Middle",
		ShortDesc: "Middle band: 20-day SMA",
		LongDesc:  "Middle Bollinger Band. 20-day SMA. Price crossing above/below middle band = trend change signal.",
		Category:  CategoryVolatility,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/b/bollingerbands.asp",
	},
	{
		ID:        "bb_lower",
		Name:      "Bollinger Lower",
		ShortDesc: "Lower band: SMA20 - 2σ - near = oversold",
		LongDesc:  "Lower Bollinger Band. SMA20 minus 2 standard deviations. Price near lower band = potentially oversold. Also used for volatility measurement.",
		Category:  CategoryVolatility,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/b/bollingerbands.asp",
	},
	{
		ID:        "bb_bandwidth",
		Name:      "BB Bandwidth",
		ShortDesc: "Band width % (20,2) - low = squeeze (potential breakout)",
		LongDesc:  "Width of Bollinger Bands (20-day, 2σ) as percentage of middle band. Low bandwidth = squeeze (low volatility, potential breakout imminent). High bandwidth = high volatility.",
		Category:  CategoryVolatility,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/b/bollingerbands.asp",
	},
	{
		ID:        "bb_pct_b",
		Name:      "BB %B",
		ShortDesc: "Position in bands (20,2) (0=lower, 1=upper) - >1 or <0 = breakout",
		LongDesc:  "Position within Bollinger Bands (20-day, 2σ). 0 = lower band, 1 = upper band. Values outside 0-1 indicate breakout. Useful for mean reversion and breakout strategies.",
		Category:  CategoryVolatility,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/b/bollingerbands.asp",
	},
	{
		ID:        "hist_vol20",
		Name:      "Historical Volatility",
		ShortDesc: "20-day annualized volatility - higher = more volatile",
		LongDesc:  "Annualized standard deviation of daily returns (20-day). Higher = more volatile. Used in options pricing and risk management.",
		Category:  CategoryVolatility,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/h/historicalvolatility.asp",
	},

	// Price Structure
	{
		ID:        "high_52w",
		Name:      "52-Week High",
		ShortDesc: "Highest price in past 252 trading days",
		LongDesc:  "Highest price over the past 252 trading days (52 weeks). Key resistance level. Breaking above = new high (bullish signal).",
		Category:  CategoryPriceStruct,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/5/52weekhighlow.asp",
	},
	{
		ID:        "low_52w",
		Name:      "52-Week Low",
		ShortDesc: "Lowest price in past 252 trading days",
		LongDesc:  "Lowest price over the past 252 trading days (52 weeks). Key support level. Breaking below = new low (bearish signal).",
		Category:  CategoryPriceStruct,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/5/52weekhighlow.asp",
	},
	{
		ID:        "is_52w_high",
		Name:      "Is 52-Week High",
		ShortDesc: "True if close equals 52-week high",
		LongDesc:  "Boolean: true if close equals the 52-week high. Identifies stocks making new highs (breakout candidates).",
		Category:  CategoryPriceStruct,
		DataType:  "boolean",
		Sortable:  false,
		WikiURL:   "https://www.investopedia.com/terms/5/52weekhighlow.asp",
	},
	{
		ID:        "is_52w_low",
		Name:      "Is 52-Week Low",
		ShortDesc: "True if close equals 52-week low",
		LongDesc:  "Boolean: true if close equals the 52-week low. Identifies stocks making new lows (potential capitulation or value trap).",
		Category:  CategoryPriceStruct,
		DataType:  "boolean",
		Sortable:  false,
		WikiURL:   "https://www.investopedia.com/terms/5/52weekhighlow.asp",
	},
	{
		ID:        "gap_pct",
		Name:      "Gap %",
		ShortDesc: "Overnight gap: (open - prev_close) / prev_close",
		LongDesc:  "Percentage gap between previous close and today's open. Positive = gap up (bullish overnight news), negative = gap down (bearish overnight news).",
		Category:  CategoryPriceStruct,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/g/gap.asp",
	},
	{
		ID:        "true_range",
		Name:      "True Range",
		ShortDesc: "Max of: H-L, |H-prevC|, |L-prevC| - volatility input",
		LongDesc:  "Maximum of: high-low, |high-previous close|, |low-previous close|. Accounts for gaps. Used in ATR calculation and volatility measurement.",
		Category:  CategoryPriceStruct,
		DataType:  "price",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/t/truerange.asp",
	},

	// Returns
	{
		ID:        "ret_1d",
		Name:      "1-Day Return",
		ShortDesc: "Yesterday's performance %",
		LongDesc:  "Percentage return over 1 day. (close / close[1 day ago] - 1) × 100. Simplest momentum measure.",
		Category:  CategoryReturns,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/return.asp",
	},
	{
		ID:        "ret_5d",
		Name:      "5-Day Return",
		ShortDesc: "Past week's performance %",
		LongDesc:  "Percentage return over 5 trading days. Short-term momentum. Useful for identifying recent strength/weakness.",
		Category:  CategoryReturns,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/return.asp",
	},
	{
		ID:        "ret_1m",
		Name:      "1-Month Return",
		ShortDesc: "Past month's performance % (21 trading days)",
		LongDesc:  "Percentage return over 21 trading days (1 month). Short-to-medium term momentum. Common timeframe for tactical trading.",
		Category:  CategoryReturns,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/return.asp",
	},
	{
		ID:        "ret_3m",
		Name:      "3-Month Return",
		ShortDesc: "Past quarter's performance % (63 trading days)",
		LongDesc:  "Percentage return over 63 trading days (3 months). Common momentum timeframe. Used in relative strength rankings and momentum strategies.",
		Category:  CategoryReturns,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/return.asp",
	},
	{
		ID:        "ret_6m",
		Name:      "6-Month Return",
		ShortDesc: "Past half-year's performance % (126 trading days)",
		LongDesc:  "Percentage return over 126 trading days (6 months). Medium-term momentum. Useful for identifying sustained trends.",
		Category:  CategoryReturns,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/return.asp",
	},
	{
		ID:        "ret_1y",
		Name:      "1-Year Return",
		ShortDesc: "Past year's performance % (252 trading days)",
		LongDesc:  "Percentage return over 252 trading days (1 year). Long-term momentum. Used in annual performance comparisons and trend analysis.",
		Category:  CategoryReturns,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/return.asp",
	},

	// Volume
	{
		ID:        "dollar_vol",
		Name:      "Dollar Volume",
		ShortDesc: "Close × volume - split-invariant activity measure",
		LongDesc:  "Close × volume. Split-invariant measure of trading activity. More reliable than raw volume on free-tier data. Used for liquidity filtering.",
		Category:  CategoryVolume,
		DataType:  "volume",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/v/volume.asp",
	},
	{
		ID:        "avg_dollar_vol20",
		Name:      "Avg Dollar Vol 20",
		ShortDesc: "20-day average dollar volume - liquidity filter",
		LongDesc:  "20-day SMA of dollar volume. Liquidity filter. High avg_dollar_vol = more liquid, easier to enter/exit positions.",
		Category:  CategoryVolume,
		DataType:  "volume",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/v/volume.asp",
	},
	{
		ID:        "rel_volume",
		Name:      "Relative Volume",
		ShortDesc: "Volume vs 20-day average - >1 = above average",
		LongDesc:  "Volume divided by 20-day average volume. Values > 1 = above average activity (unusual interest), < 1 = below average. Good for identifying breakout confirmation.",
		Category:  CategoryVolume,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/r/relative_volume.asp",
	},
	{
		ID:        "obv",
		Name:      "OBV",
		ShortDesc: "On-balance volume - rising = accumulation",
		LongDesc:  "On-balance volume. Cumulative volume indicator. Rising OBV = accumulation (buying pressure), falling OBV = distribution (selling pressure). Confirms price trends.",
		Category:  CategoryVolume,
		DataType:  "volume",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/o/onbalancevolume.asp",
	},
	{
		ID:        "vwap_dist",
		Name:      "VWAP Distance",
		ShortDesc: "Distance from volume-weighted average price",
		LongDesc:  "Percentage distance from volume-weighted average price. Positive = trading above VWAP (bullish), negative = below VWAP (bearish). Institutional benchmark.",
		Category:  CategoryVolume,
		DataType:  "numeric",
		Sortable:  true,
		WikiURL:   "https://www.investopedia.com/terms/v/vwap.asp",
	},
}
