#!/bin/bash
# Hetzner Deployment Script for Cetus Marketdata Scanner
# Run this on a fresh Ubuntu 22.04 server

set -e

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     Cetus Marketdata Scanner - Hetzner Deployment          ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root (use sudo)"
  exit 1
fi

# Configuration
APP_USER="scanner"
APP_DIR="/opt/cetus-scanner"
REPO_URL="https://github.com/jsoprych/json_scanner.git"
SERVICE_NAME="cetus-scanner"

echo "📦 Step 1/8: Updating system packages..."
apt update && apt upgrade -y

echo "📦 Step 2/8: Installing dependencies..."
apt install -y \
  git \
  sqlite3 \
  ufw \
  nginx \
  certbot \
  python3-certbot-nginx \
  build-essential \
  curl \
  wget

echo "👤 Step 3/8: Creating application user..."
if ! id "$APP_USER" &>/dev/null; then
  useradd -m -s /bin/bash "$APP_USER"
  usermod -aG sudo "$APP_USER"
  echo "✅ User '$APP_USER' created"
else
  echo "✅ User '$APP_USER' already exists"
fi

echo "📥 Step 4/8: Cloning repository..."
if [ ! -d "$APP_DIR" ]; then
  sudo -u "$APP_USER" git clone "$REPO_URL" "$APP_DIR"
  echo "✅ Repository cloned to $APP_DIR"
else
  echo "✅ Repository already exists at $APP_DIR"
fi

echo "🔨 Step 5/8: Building application..."
cd "$APP_DIR"
sudo -u "$APP_USER" make build
echo "✅ Application built"

echo "⚙️  Step 6/8: Configuring application..."
if [ ! -f "$APP_DIR/.env" ]; then
  sudo -u "$APP_USER" cp "$APP_DIR/.env.example" "$APP_DIR/.env"
  
  # Generate secure defaults
  JWT_SECRET=$(openssl rand -hex 32)
  
  cat > "$APP_DIR/.env" << EOF
# Cetus Marketdata Scanner Configuration
# Generated by Hetzner deployment script

# Database paths
SCANNER_DB_PATH=$APP_DIR/data/cetus.db
SCANNER_STORE_DB=$APP_DIR/data/scanner.db

# Server
SCANNER_SERVE_ADDR=127.0.0.1:8080
SCANNER_AUTH_MODE=login

# Universe
SCANNER_UNIVERSE=index:r3000

# Throttling
SCANNER_RATE_LIMIT_REQUESTS=100
SCANNER_RATE_LIMIT_WINDOW=60

# JWT (for API authentication)
SCANNER_JWT_SECRET=$JWT_SECRET

# Logging
SCANNER_LOG_LEVEL=info
EOF
  
  chown "$APP_USER:$APP_USER" "$APP_DIR/.env"
  chmod 600 "$APP_DIR/.env"
  echo "✅ Configuration created"
else
  echo "✅ Configuration already exists"
fi

# Create data directory
mkdir -p "$APP_DIR/data"
chown "$APP_USER:$APP_USER" "$APP_DIR/data"
chmod 700 "$APP_DIR/data"

# Initialize empty databases if they don't exist
if [ ! -f "$APP_DIR/data/cetus.db" ]; then
  sudo -u "$APP_USER" sqlite3 "$APP_DIR/data/cetus.db" "VACUUM;"
  echo "✅ Created empty cetus.db"
fi

if [ ! -f "$APP_DIR/data/scanner.db" ]; then
  sudo -u "$APP_USER" sqlite3 "$APP_DIR/data/scanner.db" "VACUUM;"
  echo "✅ Created empty scanner.db"
fi

echo "🔧 Step 7/8: Setting up systemd service..."
cat > "/etc/systemd/system/$SERVICE_NAME.service" << EOF
[Unit]
Description=Cetus Marketdata Scanner
After=network.target

[Service]
Type=simple
User=$APP_USER
WorkingDirectory=$APP_DIR
ExecStart=$APP_DIR/bin/scanner serve
Restart=always
RestartSec=10

Environment=SCANNER_DB_PATH=$APP_DIR/data/cetus.db
Environment=SCANNER_STORE_DB=$APP_DIR/data/scanner.db
Environment=SCANNER_SERVE_ADDR=127.0.0.1:8080
Environment=SCANNER_AUTH_MODE=login

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl start "$SERVICE_NAME"
echo "✅ Service started"

echo "🔥 Step 8/8: Configuring firewall..."
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable
echo "✅ Firewall configured"

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    Deployment Complete!                      ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Access points:"
echo "   • Dashboard: http://$(hostname -I | awk '{print $1}'):8080"
echo "   • Admin Panel: http://$(hostname -I | awk '{print $1}'):8080/admin"
echo "   • API: http://$(hostname -I | awk '{print $1}'):8080/api/v1"
echo ""
echo "🔐 Default admin credentials:"
echo "   • Username: admin"
echo "   • Password: admin"
echo ""
echo "⚠️  IMPORTANT: Change the admin password immediately!"
echo ""
echo "📋 Next steps:"
echo "   1. Test the application: curl http://localhost:8080/healthz"
echo "   2. Set up domain and SSL (see docs/HETZNER_DEPLOYMENT.md)"
echo "   3. Change admin password"
echo "   4. Create additional users"
echo "   5. Configure backups"
echo ""
echo "📊 Useful commands:"
echo "   • View logs: journalctl -u $SERVICE_NAME -f"
echo "   • Restart: systemctl restart $SERVICE_NAME"
echo "   • Status: systemctl status $SERVICE_NAME"
echo "   • Stop: systemctl stop $SERVICE_NAME"
echo ""
echo "📚 Documentation: $APP_DIR/docs/HETZNER_DEPLOYMENT.md"
echo ""
